Создайте одномерный массив из 5 целых чисел от 0 до 4.

In [1]:
import numpy as np

array =  np.arange(0,5)

print(array)

[0 1 2 3 4]


Создайте двумерный массив размером 4x5, заполненный нулями.

In [4]:
array =  np.zeros((4,5))
print(array)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


Создайте одномерный массив из четных чисел от 0 до 8(включительно) с шагом 2.

In [5]:
array =  np.arange(0,9,2)
print(array)

[0 2 4 6 8]


 Создайте трехмерный массив (каждый массив должен содержать две строки и четыре столбца) и определите его количество измерений.

In [6]:
arr =  np.zeros((3,2,4))
dimensions =  arr.ndim
print(arr)
print("Количество измерений:", dimensions)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
Количество измерений: 3


Повторите созданный массив с элементами(1, 2, 3) 4 раза вдоль оси 0(строки) и дополнительно, каждую строку массива увеличьте по размеру в два раза с те же элементами (вдоль оси 1(столбцы)), и еще,  дополнительно, сделайте этот массив двумерным

In [7]:
original_array = np.array([1, 2, 3])

tiled_array =  np.tile(original_array,(2,4,2))

print("Исходный массив:")
print(original_array)

print("Массив с повторенными элементами:")
print(tiled_array)

Исходный массив:
[1 2 3]
Массив с повторенными элементами:
[[[1 2 3 1 2 3]
  [1 2 3 1 2 3]
  [1 2 3 1 2 3]
  [1 2 3 1 2 3]]

 [[1 2 3 1 2 3]
  [1 2 3 1 2 3]
  [1 2 3 1 2 3]
  [1 2 3 1 2 3]]]


Есть два массива arr1 и arr2 размером 3x3. Выполните поэлементное сложение этих двух массивов и сохраните результат в массив result_add.

In [8]:
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

arr2 = np.array([[9, 8, 7],
                 [6, 5, 4],
                 [3, 2, 1]])

result_add =  arr1+arr2

print(result_add)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


Есть массив grades из оценок студентов (от 0 до 100). Преобразуйте тип данных массива grades на float . Затем напишите код, который увеличит все оценки более 50 на 10%.

In [9]:
grades = np.array([75, 45, 60, 90, 30, 85, 40])

grades =  grades.astype(float)

grades[grades>50]*=1.10

print(grades)

[82.5 45.  66.  99.  30.  93.5 40. ]


Напишите программу для выполнения поэлементного сложения массивов.

In [10]:
array1 = np.array([10, 15, 20, 25])
array2 = np.array([2, 3, 4, 5])

result = np.add(array1, array2)

print("Результат сложения массивов:", result)

Результат сложения массивов: [12 18 24 30]


Замените все отрицательные значения в массиве arr на 0.

In [11]:
arr = np.array([-1, 2, -3, 4, -5])

modified_arr = np.where(arr<0, 0, arr)# замените все отрицательные значения в массиве на 0

print("Исходный массив:")
print(arr)
print("Модифицированный массив:")
print(modified_arr)

Исходный массив:
[-1  2 -3  4 -5]
Модифицированный массив:
[0 2 0 4 0]


Найти стандартное отклонение и дисперсию элементов массива

In [12]:
arr = np.array([5, 8, 12, 15, 18])

result1 = np.std(arr) # стандартное отклонение
result2 = np.var(arr) # дисперсия

print(f"Стандартное отклонение: {result1}\nДисперсия: {result2}")

Стандартное отклонение: 4.673328578219169
Дисперсия: 21.840000000000003


Представим, что у вас есть данные о ежедневных изменениях стоимости акций компании. Используйте методы для анализа финансовых показателей. Найдите изменение цен за каждый день, а также дни с минимальным и максимальным изменением. (Внимание: Не забудьте что когда вы ищите изменение в ценах, то кол-во значений уменьшается на 1, т.к. первое значение не с чем сравнивать.)

In [13]:
stock_prices = np.array([50, 55, 60, 52, 48, 65, 70])
days = np.array(['понедельник', 'вторник', 'среда', 'четверг', 'пятница', 'суббота', 'воскресенье'])

daily_returns = np.diff(stock_prices) # Изменения цен за день
best_day = days[np.argmax(stock_prices)-1] # День с максимальным приростом
worst_day = days[np.argmin(stock_prices)-1] # День с минимальным приростом


print(f"Изменения цен за день: {daily_returns}")
print(f"Лучший день: {best_day}")
print(f"Худший день: {worst_day}")

Изменения цен за день: [ 5  5 -8 -4 17  5]
Лучший день: суббота
Худший день: четверг


Представим, что у вас есть данные о температуре воздуха в течение года. Используйте методы для выявления тенденций и крайних значений. Найди размах температур, а также индексы минимальной и максимальной температуры.

In [14]:
temperature_data = np.array([20, 22, 25, 18, 30, 28, 35, 22, 15, 10, 5, 12])

temperature_range = np.ptp(temperature_data) # Размах температур (максимальная - минимальная)
coldest_day = np.argmin(temperature_data) # Индекс самого холодного дня
hottest_day = np.argmax(temperature_data) # Индекс самого теплого дня

print(f"Размах температур: {temperature_range}")
print(f"Индекс самого холодного дня: {coldest_day}")
print(f"Индекс самого теплого дня: {hottest_day}")

Размах температур: 30
Индекс самого холодного дня: 10
Индекс самого теплого дня: 6


Вам предоставлен массив доходов отдельных инвесторов за год. Необходимо рассчитать медиану доходов и выполнить дополнительные шаги:

Найти медиану доходов.
Определить, сколько инвесторов заработали выше медианного значения, а сколько ниже.
Найти разброс доходов для инвесторов, заработавших выше медианы.

In [15]:
income_data = np.array([40, 55, 60, 75, 80, 85, 90, 100, 120, 150])

median_income = np.median(income_data) # Медиана доходов

above_median =  income_data[income_data>median_income]# Инвесторы, заработавшие выше медианы
below_median =  income_data[income_data<median_income]# Инвесторы, заработавшие ниже медианы

income_range_above_median =  np.ptp(above_median)# Разброс доходов для инвесторов, заработавших выше медианы

print("Медиана доходов:", median_income)
print("Инвесторы, заработавшие выше медианы:", above_median)
print("Инвесторы, заработавшие ниже медианы:", below_median)
print("Разброс доходов для инвесторов, заработавших выше медианы:", income_range_above_median)

Медиана доходов: 82.5
Инвесторы, заработавшие выше медианы: [ 85  90 100 120 150]
Инвесторы, заработавшие ниже медианы: [40 55 60 75 80]
Разброс доходов для инвесторов, заработавших выше медианы: 65


Напишите функцию most_frequent_number(arr), которая находит наиболее часто встречающее число и количество его вхождений

In [16]:
def most_frequent_number(arr):
    bin_counts = np.bincount(arr) # подсчет встреченных элементов
    most_frequent_index = np.argmax(bin_counts) # найдите индекс максимального значения встреченных элементов
    occurrences = np.max(bin_counts) # получите количество вхождений наиболее часто встречающегося числа
    return most_frequent_index, occurrences

arr = np.array([1, 2, 3, 1, 2, 1, 4, 5, 4, 3, 3])
result_number, result_occurrences = most_frequent_number(arr)

print(f"Наиболее часто встречающееся число: {result_number}")
print(f"Количество вхождений: {result_occurrences}")

Наиболее часто встречающееся число: 1
Количество вхождений: 3


 Удалите из массива arr все элементы, которые встречаются более одного раза.

In [17]:
arr = np.array([3, 2, 4, 1, 5, 2, 6, 4, 7])

unique_elements, counts = np.unique(arr, return_counts = True) # нахождение уникальных обьектов и кол-во их появлений
elements_to_remove = unique_elements[counts>1] # создание массива со значениями для удаления

filtered_arr = arr[~np.isin(arr, elements_to_remove)] # возвращение значений которые есть в arr, но нет в elements_to_remove, т.е. удаление нужных нам значений

print("Исходный массив:", arr)
print("Массив после удаления элементов, встречающихся более одного раза:", filtered_arr)

Исходный массив: [3 2 4 1 5 2 6 4 7]
Массив после удаления элементов, встречающихся более одного раза: [3 1 5 6 7]
